Repository akshaykumar23399/Hacktoberfest-Online-Meetup-in-UIET-MDU-, pull requests merged in 2020-10, with the labels that each got.

#15 Create GameOfLife.go
  Game Of Life/GameOfLife.go
Labels: hacktoberfest-accepted

#14 Create helloworld.rb
  helloworld.rb
Labels: hacktoberfest-accepted

#13 coded a page in HTML
  Page_scrnsht.jpg
  back.jpg
  hi .html
  tee.jpg
Labels: hacktoberfest-accepted

#12 Hello_World.js
  Hello_world.js
Labels: hacktoberfest-accepted

#11 second file
  first.java
  second.java
  third.java
Labels: hacktoberfest-accepted

#10 banking_systme.cpp
  banking_system.cpp
Labels: hacktoberfest-accepted

#9 hello-world-in-python.py
  hello-world-in-python.py
Labels: hacktoberfest-accepted

#8 Update README.md
  README.md
Labels: hacktoberfest-accepted

#7 Hello Hello hello
  Hello_world.py
Labels: hacktoberfest-accepted

#16 Added a pattern program
  PATTERN.CPP
Labels: hacktoberfest-accepted

#17 Create akshay.html
  akshay.html
Labels: hacktoberfest-accepted

#21 dijkstra added
  Dijkstra_Khattar_Style.cpp
Labels: hacktoberfest-accepted

#20 Create Hello_world.go
  Addition.py
  Addition_2.py
  Addtion.js
  Hello_world.go
Labels: enhancement, good first issue, hacktoberfest-accepted

#19 Update README.md
  README.md
Labels: good first issue, hacktoberfest-accepted

#18 Create JS_Hello_World.js
  JS_Hello_World.js
Labels: good first issue, hacktoberfest-accepted
